# This is a basic workflow to help you get started with Actions

name: Branch Sync

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: 
      - main
      - staging

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  sync-branches:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Sync Branches
        run: >-
          if [ $GITHUB_REF = 'refs/heads/staging' ]; then
            git checkout develop && git pull && git merge staging && git push
          elif [ $GITHUB_REF = 'refs/heads/main' ]; then
            git checkout develop && git pull && git merge main && git push
            git checkout staging && git pull && git merge main && git push
          fi
