name: Sync Back to Develop

on:
  push:
    branches:
      - main

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - uses: actions/checkout@v3
      - run: "echo ⚙️ synching branches"
      - run: "echo ${{ github.ref_name }}"
        
