name: Sync branches [staging -> develop]
on:
  push:
    branches:
      - "staging"
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge staging -> develop
        uses: devmasx/merge-branch@master
        with:
          type: now
          label_name: "automerge"
          from_branch: staging
          target_branch: develop
          message: Merge staging to develop
          disable_fastforwards: "false"
          github_token: ${{ secrets.GITHUB_TOKEN }}
